name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Generate Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/renaud11232/feur
          tags: latest
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and upload Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64